name: publish

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install build tool
      run: npm install -g pnpm
    - name: Install Dependencies
      run: pnpm i
    - name: Generate pages
      run: pnpm run build
    - name: Add CNAME
      run: echo "v3-docs.vuejs-korea.org" > .vitepress/dist/CNAME
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist/
